version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: nyu
    container_name: lab-flask-bdd
    # ports:
    #   - 8080:8080
    volumes:
      - ..:/app
    command: sleep infinity
    environment:
      FLASK_APP: service:app
      FLASK_ENV: development
      GUNICORN_BIND: "0.0.0.0:8000"
      BINDING_CLOUDANT: '{"username":"admin","password":"pass","host":"couchdb","port":5984,"url":"http://admin:pass@couchdb:5984"}'
    networks:
      - dev
    depends_on:
      - couchdb

  # CouchDB database service at: http://127.0.0.1:5984/_utils
  couchdb:
    image: couchdb:latest
    hostname: couchdb
    container_name: lab-flask-bdd-couchdb
    ports:
      - 5984:5984
    volumes:
      - couchdb:/opt/couchdb/data
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: pass
    networks:
      - dev

  # Create a few databases needed by CouchDB
  setup:
    image: couchdb:latest
    command: >
      bash -c "echo '*** SETUP: waiting 15 seconds for couchdb to initialize...'; sleep 15
      && curl -X PUT http://admin:pass@couchdb:5984/_users
      && curl -X PUT http://admin:pass@couchdb:5984/_replicator
      && curl -X PUT http://admin:pass@couchdb:5984/_global_changes"
    networks:
      - dev
    depends_on:
      - couchdb   

volumes:
  couchdb:

networks:
  dev:
